import AntichainOfGivenSize.BasicLemmas
import AntichainOfGivenSize.LowerBound.SignedPowers
import AntichainOfGivenSize.Section6.Core
import Mathlib.Data.Nat.Log

open scoped BigOperators
open Finset

namespace AntichainOfGivenSize

/-!
# The block-count lower bound for generated ideals

Inclusion-exclusion writes the cardinality of an ideal generated by `q` sets
as a signed sum of one power of two for every nonempty subfamily.  There are
`2^q - 1` such subfamilies, so the signed-power theorem bounds the binary
block count by `2^q - 1`.
-/

/-- The binary block count of an ideal generated by `q` sets is strictly
smaller than `2^q`. -/
theorem binaryBlockCount_generatedIdeal_add_one_le_two_pow
    {V : Type*} [DecidableEq V] (generators : Finset (Finset V)) :
    binaryBlockCount (generatedIdeal generators).card + 1 ≤
      2 ^ generators.card := by
  let subfamilies := generators.powerset.filter (·.Nonempty)
  let exponent : ↥subfamilies → ℕ := fun t ↦
    (t.1.inf' (Finset.mem_filter.1 t.2).2 id).card
  let positive : Finset ↥subfamilies :=
    Finset.univ.filter fun t ↦ Odd t.1.card
  let negative : Finset ↥subfamilies :=
    Finset.univ.filter fun t ↦ ¬Odd t.1.card
  let term : ↥subfamilies → ℤ := fun t ↦
    (-1 : ℤ) ^ (t.1.card + 1) * (2 : ℤ) ^ exponent t

  have hIE : ((generatedIdeal generators).card : ℤ) =
      ∑ t : ↥subfamilies, term t := by
    simpa [subfamilies, exponent, term, generatedIdeal,
      Section6.generatedIdealIdx] using
        (Section6.generatedIdealIdx_card_inclusionExclusion generators id)

  have hpositive : (∑ t ∈ positive, term t) =
      ∑ t ∈ positive, (2 : ℤ) ^ exponent t := by
    apply Finset.sum_congr rfl
    intro t ht
    have htodd : Odd t.1.card := (Finset.mem_filter.1 ht).2
    simp only [term, htodd.add_one.neg_one_pow, one_mul]

  have hnegative : (∑ t ∈ negative, term t) =
      -(∑ t ∈ negative, (2 : ℤ) ^ exponent t) := by
    rw [← Finset.sum_neg_distrib]
    apply Finset.sum_congr rfl
    intro t ht
    have hteven : Even t.1.card :=
      Nat.not_odd_iff_even.mp (Finset.mem_filter.1 ht).2
    simp only [term, hteven.add_one.neg_one_pow, neg_mul, one_mul]

  have hsplit : (∑ t : ↥subfamilies, term t) =
      (∑ t ∈ positive, (2 : ℤ) ^ exponent t) -
        ∑ t ∈ negative, (2 : ℤ) ^ exponent t := by
    rw [← Finset.sum_filter_add_sum_filter_not Finset.univ
      (fun t : ↥subfamilies ↦ Odd t.1.card) term]
    rw [show Finset.univ.filter (fun t : ↥subfamilies ↦ Odd t.1.card) =
      positive by rfl]
    rw [show Finset.univ.filter (fun t : ↥subfamilies ↦ ¬Odd t.1.card) =
      negative by rfl]
    rw [hpositive, hnegative, sub_eq_add_neg]

  have hbalanceInt :
      (∑ t ∈ positive, (2 : ℤ) ^ exponent t) =
        ((generatedIdeal generators).card : ℤ) +
          ∑ t ∈ negative, (2 : ℤ) ^ exponent t := by
    rw [hIE, hsplit]
    ring
  have hbalanceNat :
      (∑ t ∈ positive, (2 : ℕ) ^ exponent t) =
        (generatedIdeal generators).card +
          ∑ t ∈ negative, (2 : ℕ) ^ exponent t := by
    exact_mod_cast hbalanceInt

  have hblocks := binaryBlockCount_signedPowerFinsets
    (generatedIdeal generators).card positive negative exponent exponent hbalanceNat
  have hcards : positive.card + negative.card = subfamilies.card := by
    simpa [positive, negative] using
      (Finset.card_filter_add_card_filter_not
        (s := (Finset.univ : Finset ↥subfamilies))
        (p := fun t : ↥subfamilies ↦ Odd t.1.card))
  rw [hcards] at hblocks

  have hsubfamilies : subfamilies.card = 2 ^ generators.card - 1 := by
    dsimp only [subfamilies]
    have hempty : generators.powerset.filter (·.Nonempty) =
        generators.powerset.erase ∅ := by
      ext s
      simp [Finset.nonempty_iff_ne_empty, and_comm]
    rw [hempty, Finset.card_erase_of_mem]
    · simp
    · simp
  rw [hsubfamilies] at hblocks
  have hpow : 0 < 2 ^ generators.card := pow_pos (by omega) _
  omega

/-- Exact natural-number form of the lower bound after minimizing the
generator family. -/
theorem binaryBlockCount_add_one_le_two_pow_alpha (n : ℕ) :
    binaryBlockCount n + 1 ≤ 2 ^ alpha n := by
  rcases alpha_hasGeneratorCount n with
    ⟨m, generators, hsize, hcard⟩
  simpa [hsize, hcard] using
    binaryBlockCount_generatedIdeal_add_one_le_two_pow generators

/-- A ceiling-logarithm version, slightly stronger than the paper's real-log
formulation. -/
theorem clog_binaryBlockCount_le_alpha (n : ℕ) :
    Nat.clog 2 (binaryBlockCount n + 1) ≤ alpha n := by
  exact Nat.clog_le_of_le_pow (binaryBlockCount_add_one_le_two_pow_alpha n)

/-- Corollary 3.6, directly for generated ideals:
`log₂(blockCount(n) + 1) ≤ alpha(n)`. -/
theorem logb_binaryBlockCount_le_alpha (n : ℕ) :
    Real.logb 2 ((binaryBlockCount n + 1 : ℕ) : ℝ) ≤ (alpha n : ℝ) := by
  have hcountReal :
      ((binaryBlockCount n + 1 : ℕ) : ℝ) ≤ (2 : ℝ) ^ alpha n := by
    exact_mod_cast binaryBlockCount_add_one_le_two_pow_alpha n
  calc
    Real.logb 2 ((binaryBlockCount n + 1 : ℕ) : ℝ) ≤
        Real.logb 2 ((2 : ℝ) ^ alpha n) :=
      Real.logb_le_logb_of_le (by norm_num) (by positivity) hcountReal
    _ = (alpha n : ℝ) := by
      rw [Real.logb_pow]
      norm_num [Real.logb_self_eq_one]

end AntichainOfGivenSize
