import AntichainOfGivenSize.Section6.IndexedBounds
import Mathlib.Data.Fintype.Sigma

/-!
# Venn-profile normal form

This file gives an exact arithmetic description of ideals generated by a
finite family.  A Venn profile records, for every set of generator indices,
how many ground-set elements belong to exactly those generators.

The final definitions state an infinitely-often
`(log log n)^(1 + epsilon)` lower-bound target and an equivalent obstruction
in terms of Venn profiles.  This module isolates that equivalence; the
stronger unconditional quadratic-over-log lower bound is assembled in
`LowerBound.Matching`.
-/

open scoped BigOperators
open Finset

namespace AntichainOfGivenSize.VennProfile

variable {I V : Type*} [Fintype I] [DecidableEq I]
  [Fintype V] [DecidableEq V]

/-- The set of generator indices containing a ground-set element. -/
def membershipPattern (G : I → Finset V) (v : V) : Finset I :=
  Finset.univ.filter fun i ↦ v ∈ G i

/-- Number of ground-set elements having exactly membership pattern `A`. -/
def atomCount (G : I → Finset V) (A : Finset I) : ℕ :=
  (Finset.univ.filter fun v ↦ membershipPattern G v = A).card

/-- Intersection size encoded by Venn-atom multiplicities. -/
def profileIntersectionSize (x : Finset I → ℕ) (J : Finset I) : ℕ :=
  ∑ A ∈ Finset.univ.powerset.filter (J ⊆ ·), x A

/-- Inclusion–exclusion expression encoded by a Venn profile. -/
def vennExpression (x : Finset I → ℕ) : ℤ :=
  ∑ J : Finset.univ.powerset.filter (fun J : Finset I ↦ J.Nonempty),
    (-1 : ℤ) ^ (J.1.card + 1) * (2 : ℤ) ^ profileIntersectionSize x J.1

omit [DecidableEq I] [Fintype V] in
@[simp] theorem mem_membershipPattern (G : I → Finset V) (v : V) (i : I) :
    i ∈ membershipPattern G v ↔ v ∈ G i := by
  simp [membershipPattern]

/-- Generator intersections are disjoint unions of the Venn atoms whose
patterns contain the requested indices. -/
theorem inf_card_eq_profileIntersectionSize
    (G : I → Finset V) (J : Finset I) (hJ : J.Nonempty) :
    (J.inf' hJ G).card = profileIntersectionSize (atomCount G) J := by
  classical
  unfold profileIntersectionSize atomCount
  rw [Finset.sum_card_fiberwise_eq_card_filter]
  congr 1
  ext v
  simp [membershipPattern]
  constructor
  · intro h i hi
    exact Finset.mem_filter.2 ⟨Finset.mem_univ _, h i hi⟩
  · intro h i hi
    exact (Finset.mem_filter.1 (h hi)).2

/-- Forward Venn normal form for any finitely indexed family. -/
theorem generatedIdealIdx_card_eq_vennExpression (G : I → Finset V) :
    ((AntichainOfGivenSize.Section6.generatedIdealIdx Finset.univ G).card : ℤ) =
      vennExpression (atomCount G) := by
  rw [AntichainOfGivenSize.Section6.generatedIdealIdx_card_inclusionExclusion]
  unfold vennExpression
  apply Finset.sum_congr rfl
  intro J _hJ
  congr 2
  exact inf_card_eq_profileIntersectionSize G J.1
    (Finset.mem_filter.1 J.2).2

/-- A family of exactly `q` generators yields a profile on `Fin q`. -/
theorem hasGeneratorCount_imp_exists_vennProfile {n q : ℕ}
    (h : AntichainOfGivenSize.HasGeneratorCount n q) :
    ∃ x : Finset (Fin q) → ℕ, (n : ℤ) = vennExpression x := by
  rcases h with ⟨m, S, hsize, hcard⟩
  let e : ↑S ≃ Fin q := Fintype.equivFinOfCardEq (by simpa using hcard)
  let G : Fin q → Finset (Fin m) := fun i ↦ (e.symm i).1
  refine ⟨atomCount G, ?_⟩
  rw [← generatedIdealIdx_card_eq_vennExpression G]
  norm_cast
  rw [← hsize]
  apply congrArg Finset.card
  rw [AntichainOfGivenSize.generatedIdealIdx_eq_generatedIdeal_image]
  have himage : Finset.univ.image G = S := by
    ext A
    simp only [Finset.mem_image, Finset.mem_univ, true_and]
    constructor
    · rintro ⟨i, rfl⟩
      exact (e.symm i).2
    · intro hA
      let a : ↑S := ⟨A, hA⟩
      refine ⟨e a, ?_⟩
      simp [G, a]
  rw [himage]

/-! Conversely, create `x A` elements in Venn atom `A`. -/

/-- Canonical ground-set elements realizing the multiplicities `x`. -/
def ProfilePoint (x : Finset I → ℕ) := Σ A : Finset I, Fin (x A)

instance (x : Finset I → ℕ) : Fintype (ProfilePoint x) := by
  unfold ProfilePoint
  exact Sigma.instFintype

noncomputable instance (x : Finset I → ℕ) : DecidableEq (ProfilePoint x) :=
  Classical.decEq _

/-- The canonical generator indexed by `i` contains precisely the profile
points whose patterns contain `i`. -/
noncomputable def profileGenerator (x : Finset I → ℕ) (i : I) :
    Finset (ProfilePoint x) :=
  Finset.univ.filter fun p ↦ i ∈ p.1

@[simp] theorem membershipPattern_profileGenerator
    (x : Finset I → ℕ) (p : ProfilePoint x) :
    membershipPattern (profileGenerator x) p = p.1 := by
  ext i
  simp [membershipPattern, profileGenerator]

@[simp] theorem atomCount_profileGenerator
    (x : Finset I → ℕ) (A : Finset I) :
    atomCount (profileGenerator x) A = x A := by
  classical
  unfold atomCount
  simp only [membershipPattern_profileGenerator]
  let e : {p : ProfilePoint x // p.1 = A} ≃ Fin (x A) :=
    { toFun := fun p ↦ p.2 ▸ p.1.2
      invFun := fun j ↦ ⟨⟨A, j⟩, rfl⟩
      left_inv := by
        rintro ⟨⟨B, j⟩, hB⟩
        change B = A at hB
        cases hB
        rfl
      right_inv := by intro j; rfl }
  calc
    (Finset.univ.filter fun p : ProfilePoint x ↦ p.1 = A).card =
        Fintype.card {p : ProfilePoint x // p.1 = A} := by
      symm
      apply Fintype.card_of_subtype
      simp
    _ = Fintype.card (Fin (x A)) := Fintype.card_congr e
    _ = x A := Fintype.card_fin _

/-- The canonical family realizes its profile expression. -/
theorem generatedIdealIdx_profileGenerator_card (x : Finset I → ℕ) :
    ((AntichainOfGivenSize.Section6.generatedIdealIdx Finset.univ
        (profileGenerator x)).card : ℤ) = vennExpression x := by
  rw [generatedIdealIdx_card_eq_vennExpression]
  have hatom : atomCount (profileGenerator x) = x := by
    funext A
    exact atomCount_profileGenerator x A
  rw [hatom]

/-- A natural number is represented by a `k`-coordinate Venn profile. -/
def HasVennProfile (n k : ℕ) : Prop :=
  ∃ x : Finset (Fin k) → ℕ, (n : ℤ) = vennExpression x

theorem hasVennProfile_of_hasGeneratorCount {n k : ℕ}
    (h : AntichainOfGivenSize.HasGeneratorCount n k) : HasVennProfile n k :=
  hasGeneratorCount_imp_exists_vennProfile h

/-- Any profile with `k` coordinates constructs an ideal generated by at
most `k` sets. -/
theorem alpha_le_of_hasVennProfile {n k : ℕ} (h : HasVennProfile n k) :
    AntichainOfGivenSize.alpha n ≤ k := by
  rcases h with ⟨x, hx⟩
  have hcardInt := generatedIdealIdx_profileGenerator_card x
  have hcard :
      (AntichainOfGivenSize.Section6.generatedIdealIdx Finset.univ
        (profileGenerator x)).card = n := by
    exact_mod_cast hcardInt.trans hx.symm
  have hbound := AntichainOfGivenSize.alpha_generatedIdealIdx_univ_card_le
    (G := profileGenerator x)
  rw [hcard] at hbound
  simpa using hbound

/-- Exact bounded Venn-profile normal form for `alpha`. -/
theorem alpha_le_iff_exists_bounded_vennProfile (n q : ℕ) :
    AntichainOfGivenSize.alpha n ≤ q ↔
      ∃ k : ℕ, k ≤ q ∧ HasVennProfile n k := by
  constructor
  · intro h
    refine ⟨AntichainOfGivenSize.alpha n, h, ?_⟩
    exact hasVennProfile_of_hasGeneratorCount
      (AntichainOfGivenSize.alpha_hasGeneratorCount n)
  · rintro ⟨k, hk, hprofile⟩
    exact (alpha_le_of_hasVennProfile hprofile).trans hk

/-! ## An infinitely-often power strengthening -/

/-- The scale `(log₂(log₂ n))^(1 + ε)` at a natural input. -/
noncomputable def superLogLogPowerScale (ε : ℝ) (n : ℕ) : ℝ :=
  (Real.logb 2 (Real.logb 2 (n : ℝ))) ^ (1 + ε)

/-- For fixed constants `ε` and `c`, the power improvement holds
for arbitrarily large inputs.  Positivity assumptions on the constants are
kept separate so that this exact pointwise property has a simple normal form. -/
def SuperLogLogPowerLowerBoundInfinitelyOften (ε c : ℝ) : Prop :=
  ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧
    c * superLogLogPowerScale ε n ≤ (AntichainOfGivenSize.alpha n : ℝ)

/-- The same bound, expressed by excluding every Venn profile whose
number of coordinates lies strictly below the desired real lower bound. -/
def VennProfileObstructionInfinitelyOften (ε c : ℝ) : Prop :=
  ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧
    ∀ k : ℕ, (k : ℝ) < c * superLogLogPowerScale ε n →
      ¬ HasVennProfile n k

/-- A real lower bound for `alpha n` is exactly the exclusion of every Venn
profile with a number of coordinates below that bound. -/
theorem real_le_alpha_iff_no_vennProfile_below (n : ℕ) (t : ℝ) :
    t ≤ (AntichainOfGivenSize.alpha n : ℝ) ↔
      ∀ k : ℕ, (k : ℝ) < t → ¬ HasVennProfile n k := by
  constructor
  · intro ht k hk hprofile
    have hak : AntichainOfGivenSize.alpha n ≤ k :=
      alpha_le_of_hasVennProfile hprofile
    have hakReal : (AntichainOfGivenSize.alpha n : ℝ) ≤ (k : ℝ) := by
      exact_mod_cast hak
    exact (not_lt_of_ge ht) (hakReal.trans_lt hk)
  · intro h
    by_contra hnot
    have hlt : (AntichainOfGivenSize.alpha n : ℝ) < t :=
      lt_of_not_ge hnot
    exact (h (AntichainOfGivenSize.alpha n) hlt)
      (hasVennProfile_of_hasGeneratorCount
        (AntichainOfGivenSize.alpha_hasGeneratorCount n))

/-- The fixed-constant infinitely-often power target is equivalent to the
Venn-profile obstruction formulation. -/
theorem superLogLogPowerLowerBoundInfinitelyOften_iff_vennProfileObstruction
    (ε c : ℝ) :
    SuperLogLogPowerLowerBoundInfinitelyOften ε c ↔
      VennProfileObstructionInfinitelyOften ε c := by
  constructor
  · intro h N
    rcases h N with ⟨n, hn, hbound⟩
    exact ⟨n, hn,
      (real_le_alpha_iff_no_vennProfile_below n
        (c * superLogLogPowerScale ε n)).1 hbound⟩
  · intro h N
    rcases h N with ⟨n, hn, hobstruction⟩
    exact ⟨n, hn,
      (real_le_alpha_iff_no_vennProfile_below n
        (c * superLogLogPowerScale ε n)).2 hobstruction⟩

/-- Named target: some fixed `ε > 0` and `c > 0` give the
power improvement for arbitrarily large `n`. -/
def HasSuperLogLogPowerLowerBoundInfinitelyOften : Prop :=
  ∃ ε c : ℝ, 0 < ε ∧ 0 < c ∧
    SuperLogLogPowerLowerBoundInfinitelyOften ε c

/-- Existential version of the exact profile-obstruction reformulation. -/
theorem hasSuperLogLogPowerLowerBoundInfinitelyOften_iff :
    HasSuperLogLogPowerLowerBoundInfinitelyOften ↔
      ∃ ε c : ℝ, 0 < ε ∧ 0 < c ∧
        VennProfileObstructionInfinitelyOften ε c := by
  simp only [HasSuperLogLogPowerLowerBoundInfinitelyOften,
    superLogLogPowerLowerBoundInfinitelyOften_iff_vennProfileObstruction]

end AntichainOfGivenSize.VennProfile
