name = "AntichainOfGivenSize"
version = "0.1.0"
defaultTargets = ["AntichainOfGivenSize"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "AntichainOfGivenSize"
roots = ["AntichainOfGivenSize"]
