import Mathlib

open Finset

namespace Zhang

/-!
The arithmetic core of Claim 6.4.  For each bit position `a < q`, the
construction selects a remainder block of size `a` or `a + 1` according to
the `a`th bit of `d`.  Since the selected blocks are pairwise disjoint, the
ideal they generate has size

`1 + ∑ a, (2 ^ selectedBlockSize d a - 1)`.

The theorem `remainderZ_eq` evaluates this number, and
`exists_remainderZ_modEq` is the residue-selection statement used at each
stage of the block construction.
-/

theorem mem_bitIndices_iff_testBit (n i : ℕ) :
    i ∈ n.bitIndices ↔ n.testBit i = true := by
  simp

/-- The value represented by the lowest `q` bits of `d`. -/
def lowBitsValue (q d : ℕ) : ℕ :=
  ∑ a : Fin q, if d.testBit a then 2 ^ a.val else 0

theorem mem_bitIndices_lt_of_lt_two_pow {q d i : ℕ}
    (hd : d < 2 ^ q) (hi : i ∈ d.bitIndices) : i < q := by
  apply (Nat.pow_lt_pow_iff_right (by omega : 1 < 2)).mp
  exact (Nat.two_pow_le_of_mem_bitIndices hi).trans_lt hd

theorem map_lowBits_eq_bitIndices {q d : ℕ} (hd : d < 2 ^ q) :
    ((Finset.univ.filter fun a : Fin q ↦ d.testBit a).map Fin.valEmbedding) =
      d.bitIndices.toFinset := by
  ext i
  constructor
  · intro hi
    simp only [Finset.mem_map, Finset.mem_filter, Finset.mem_univ, true_and,
      List.mem_toFinset] at hi ⊢
    rcases hi with ⟨a, ha, rfl⟩
    exact (mem_bitIndices_iff_testBit d a).2 (by simpa using ha)
  · intro hi
    have hi' : i ∈ d.bitIndices := by simpa using hi
    let a : Fin q := ⟨i, mem_bitIndices_lt_of_lt_two_pow hd hi'⟩
    refine Finset.mem_map.2 ⟨a, ?_, rfl⟩
    simp [a, (mem_bitIndices_iff_testBit d i).1 hi']

theorem lowBitsValue_eq {q d : ℕ} (hd : d < 2 ^ q) : lowBitsValue q d = d := by
  rw [lowBitsValue, ← Finset.sum_filter]
  calc
    ∑ a ∈ Finset.univ.filter (fun a : Fin q ↦ d.testBit a), 2 ^ a.val =
        ∑ i ∈ (Finset.univ.filter fun a : Fin q ↦ d.testBit a).map
          Fin.valEmbedding, 2 ^ i := by
      simp only [Finset.sum_map, Fin.valEmbedding_apply]
    _ = ∑ i ∈ d.bitIndices.toFinset, 2 ^ i := by
      rw [map_lowBits_eq_bitIndices hd]
    _ = d := by
      simp [List.sum_toFinset _ Nat.bitIndices_sorted.nodup,
        Nat.sum_map_two_pow_bitIndices]

/-- Size of the remainder block selected in bit position `a`. -/
def selectedBlockSize {q : ℕ} (d : ℕ) (a : Fin q) : ℕ :=
  a.val + if d.testBit a then 1 else 0

/-- `Z(d)`: cardinality of the ideal generated by the selected, pairwise
disjoint remainder blocks.  Their powersets share only the empty set. -/
def remainderZ (q d : ℕ) : ℕ :=
  1 + ∑ a : Fin q, (2 ^ selectedBlockSize d a - 1)

theorem self_le_two_pow (q : ℕ) : q ≤ 2 ^ q := by
  induction q with
  | zero => simp
  | succ q ih =>
      rw [pow_succ]
      have hpow : 1 ≤ 2 ^ q := Nat.one_le_two_pow
      omega

theorem sum_two_pow_fin (q : ℕ) :
    (∑ a : Fin q, 2 ^ a.val) = 2 ^ q - 1 := by
  rw [Fin.sum_univ_eq_sum_range]
  have h := geom_sum_mul_add (1 : ℕ) q
  norm_num at h ⊢
  omega

theorem sum_two_pow_sub_one_fin (q : ℕ) :
    (∑ a : Fin q, (2 ^ a.val - 1)) = 2 ^ q - 1 - q := by
  have hadd :
      (∑ a : Fin q, (2 ^ a.val - 1)) + q = ∑ a : Fin q, 2 ^ a.val := by
    calc
      (∑ a : Fin q, (2 ^ a.val - 1)) + q =
          (∑ a : Fin q, (2 ^ a.val - 1)) + ∑ _a : Fin q, 1 := by simp
      _ = ∑ a : Fin q, ((2 ^ a.val - 1) + 1) := by
        rw [Finset.sum_add_distrib]
      _ = ∑ a : Fin q, 2 ^ a.val := by
        apply Finset.sum_congr rfl
        intro a _ha
        exact Nat.sub_add_cancel Nat.one_le_two_pow
  rw [sum_two_pow_fin] at hadd
  omega

theorem pow_selectedBlockSize_sub_one {q : ℕ} (d : ℕ) (a : Fin q) :
    2 ^ selectedBlockSize d a - 1 =
      (2 ^ a.val - 1) + if d.testBit a then 2 ^ a.val else 0 := by
  by_cases hbit : d.testBit a = true
  · simp only [selectedBlockSize, hbit, if_true, pow_succ]
    have hpow : 1 ≤ 2 ^ a.val := Nat.one_le_two_pow
    omega
  · have hfalse : d.testBit a = false := Bool.eq_false_of_not_eq_true hbit
    simp [selectedBlockSize, hfalse]

/-- A subtraction-free form of Claim 6.4's exact count, valid for arbitrary
`d`.  This is often the most convenient form for later modular arithmetic. -/
theorem remainderZ_add_q_eq_lowBits (q d : ℕ) :
    remainderZ q d + q = 2 ^ q + lowBitsValue q d := by
  rw [remainderZ]
  simp_rw [pow_selectedBlockSize_sub_one]
  rw [Finset.sum_add_distrib, sum_two_pow_sub_one_fin]
  change 1 + (2 ^ q - 1 - q + lowBitsValue q d) + q =
    2 ^ q + lowBitsValue q d
  have hq1 : q + 1 ≤ 2 ^ q := by
    induction q with
    | zero => simp
    | succ q ih =>
        rw [pow_succ]
        have hpow : 1 ≤ 2 ^ q := Nat.one_le_two_pow
        omega
  omega

/-- Claim 6.4's exact count, first in a form valid for arbitrary `d`. -/
theorem remainderZ_eq_lowBits (q d : ℕ) :
    remainderZ q d = 2 ^ q + lowBitsValue q d - q := by
  have hz := remainderZ_add_q_eq_lowBits q d
  have hq : q ≤ 2 ^ q + lowBitsValue q d :=
    (self_le_two_pow q).trans (Nat.le_add_right _ _)
  omega

/-- Claim 6.4(1): `Z(d) = 2^q + d - q` for a `q`-bit integer. -/
theorem remainderZ_eq {q d : ℕ} (hd : d < 2 ^ q) :
    remainderZ q d = 2 ^ q + d - q := by
  rw [remainderZ_eq_lowBits, lowBitsValue_eq hd]

/-- Claim 6.4(2): modulo `2^q`, `Z(d)` is the translate `d - q`. -/
theorem remainderZ_cast {q d : ℕ} (hd : d < 2 ^ q) :
    (remainderZ q d : ZMod (2 ^ q)) =
      (d : ZMod (2 ^ q)) - (q : ZMod (2 ^ q)) := by
  rw [remainderZ_eq hd]
  have hq : q ≤ 2 ^ q + d := (self_le_two_pow q).trans (Nat.le_add_right _ _)
  rw [Nat.cast_sub hq]
  rw [Nat.cast_add, ZMod.natCast_self]
  simp

/-- Claim 6.4(3): as `d` ranges over the `q`-bit integers, the values `Z(d)`
hit every residue modulo `2^q`. -/
theorem exists_remainderZ_cast (q : ℕ) (c : ZMod (2 ^ q)) :
    ∃ d < 2 ^ q, (remainderZ q d : ZMod (2 ^ q)) = c := by
  let d : ℕ := (c + (q : ZMod (2 ^ q))).val
  have hd : d < 2 ^ q := by
    exact ZMod.val_lt (c + (q : ZMod (2 ^ q)))
  refine ⟨d, hd, ?_⟩
  rw [remainderZ_cast hd]
  rw [show ((d : ℕ) : ZMod (2 ^ q)) = c + (q : ZMod (2 ^ q)) by
    exact ZMod.natCast_zmod_val (c + (q : ZMod (2 ^ q)))]
  abel

/-- Natural-number version of residue surjectivity. -/
theorem exists_remainderZ_modEq (q c : ℕ) :
    ∃ d < 2 ^ q, remainderZ q d ≡ c [MOD 2 ^ q] := by
  obtain ⟨d, hd, heq⟩ := exists_remainderZ_cast q (c : ZMod (2 ^ q))
  refine ⟨d, hd, ?_⟩
  exact (ZMod.natCast_eq_natCast_iff _ _ _).mp heq

end Zhang
