import ZhangSection6Core
import ZhangBasicLemmas
import Mathlib.Tactic

/-!
# Generic size bounds for indexed generating families

The block construction keeps a fixed index type even when two indexed
generators might coincide.  These lemmas therefore work directly with
`ZhangSection6.generatedIdealIdx` and never assume injectivity of `G`.
-/

open scoped BigOperators

namespace ZhangImprovedBound

variable {I V : Type*} [DecidableEq V]

/-- An indexed union of principal ideals is generated by the image family.
This is the bridge to the definition of `alpha`. -/
theorem generatedIdealIdx_eq_generatedIdeal_image
    (s : Finset I) (G : I → Finset V) :
    ZhangSection6.generatedIdealIdx s G = generatedIdeal (s.image G) := by
  ext A
  simp [ZhangSection6.generatedIdealIdx, generatedIdeal]

/-- Crude but uniform cardinality bound for an indexed family: there are at
most `s.card` principal ideals, and each contains at most every subset of the
finite vertex universe. -/
theorem generatedIdealIdx_card_le_card_mul_pow
    [Fintype V] (s : Finset I) (G : I → Finset V) :
    (ZhangSection6.generatedIdealIdx s G).card ≤
      s.card * 2 ^ Fintype.card V := by
  unfold ZhangSection6.generatedIdealIdx
  apply Finset.card_biUnion_le_card_mul
  intro i hi
  rw [Finset.card_powerset]
  exact Nat.pow_le_pow_right (by norm_num) (Finset.card_le_univ (G i))

/-- A nonempty indexed family generates a nonempty ideal (it always contains
the empty set). -/
theorem generatedIdealIdx_card_pos
    {s : Finset I} (hs : s.Nonempty) (G : I → Finset V) :
    0 < (ZhangSection6.generatedIdealIdx s G).card := by
  apply Finset.card_pos.mpr
  obtain ⟨i, hi⟩ := hs
  refine ⟨∅, Finset.mem_biUnion.mpr ⟨i, hi, ?_⟩⟩
  simp

/-- The indexed family itself supplies an `alpha` witness.  No injectivity is
needed: collapsing equal generators only decreases the image cardinality. -/
theorem alpha_generatedIdealIdx_card_le
    [Fintype V] (s : Finset I) (G : I → Finset V) :
    alpha (ZhangSection6.generatedIdealIdx s G).card ≤ s.card := by
  rw [generatedIdealIdx_eq_generatedIdeal_image]
  exact (alpha_le_of_family (s.image G)).trans Finset.card_image_le

/-- Full-index specialization of the cardinality bound. -/
theorem generatedIdealIdx_univ_card_le
    [Fintype I] [DecidableEq I] [Fintype V] (G : I → Finset V) :
    (ZhangSection6.generatedIdealIdx Finset.univ G).card ≤
      Fintype.card I * 2 ^ Fintype.card V := by
  simpa using generatedIdealIdx_card_le_card_mul_pow (Finset.univ : Finset I) G

/-- Full-index specialization of positivity. -/
theorem generatedIdealIdx_univ_card_pos
    [Fintype I] [DecidableEq I] [Nonempty I] (G : I → Finset V) :
    0 < (ZhangSection6.generatedIdealIdx Finset.univ G).card := by
  exact generatedIdealIdx_card_pos Finset.univ_nonempty G

/-- Full-index specialization of the `alpha` witness. -/
theorem alpha_generatedIdealIdx_univ_card_le
    [Fintype I] [DecidableEq I] [Fintype V] (G : I → Finset V) :
    alpha (ZhangSection6.generatedIdealIdx Finset.univ G).card ≤ Fintype.card I := by
  simpa using alpha_generatedIdealIdx_card_le (Finset.univ : Finset I) G

/-- Convert separate generator-count and universe-size bounds, together with
an already established exponential comparison, into the strict size bound
needed by the block construction. -/
theorem generatedIdealIdx_card_lt_of_mul_pow_lt
    [Fintype V] {s : Finset I} {G : I → Finset V}
    {generatorCount universeCard N n : ℕ}
    (hgenerators : s.card ≤ generatorCount)
    (huniverse : Fintype.card V ≤ universeCard)
    (hexponential : generatorCount * 2 ^ universeCard < 2 ^ N)
    (hn : 2 ^ N ≤ n) :
    (ZhangSection6.generatedIdealIdx s G).card < n := by
  have hpow : 2 ^ Fintype.card V ≤ 2 ^ universeCard := by
    exact Nat.pow_le_pow_right (by norm_num) huniverse
  calc
    (ZhangSection6.generatedIdealIdx s G).card ≤
        s.card * 2 ^ Fintype.card V :=
      generatedIdealIdx_card_le_card_mul_pow s G
    _ ≤ generatorCount * 2 ^ universeCard := Nat.mul_le_mul hgenerators hpow
    _ < 2 ^ N := hexponential
    _ ≤ n := hn

/-- A convenient pure-exponent version.  If the index count costs at most
`generatorExponent` bits, the vertex universe costs at most
`universeExponent` bits, and their sum is below `N`, then the generated ideal
has size below every `n ≥ 2^N`. -/
theorem generatedIdealIdx_card_lt_of_exponent_bounds
    [Fintype V] {s : Finset I} {G : I → Finset V}
    {generatorExponent universeExponent N n : ℕ}
    (hgenerators : s.card ≤ 2 ^ generatorExponent)
    (huniverse : Fintype.card V ≤ universeExponent)
    (hexponents : generatorExponent + universeExponent < N)
    (hn : 2 ^ N ≤ n) :
    (ZhangSection6.generatedIdealIdx s G).card < n := by
  apply generatedIdealIdx_card_lt_of_mul_pow_lt hgenerators huniverse
  · calc
      2 ^ generatorExponent * 2 ^ universeExponent =
          2 ^ (generatorExponent + universeExponent) :=
        (pow_add 2 generatorExponent universeExponent).symm
      _ < 2 ^ N := Nat.pow_lt_pow_right (by omega) hexponents
  · exact hn

end ZhangImprovedBound
