import Mathlib.Combinatorics.Enumerative.InclusionExclusion
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.Finset.Sups
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic.NormNum

open scoped BigOperators

namespace AntichainOfGivenSize.Section6

variable {ι V : Type*} [DecidableEq V]

theorem two_pow_eq_zero_zmod (k e : ℕ) (h : k ≤ e) :
    (2 : ZMod (2 ^ k)) ^ e = 0 := by
  calc
    (2 : ZMod (2 ^ k)) ^ e = 2 ^ (k + (e - k)) := by rw [Nat.add_sub_of_le h]
    _ = 2 ^ k * 2 ^ (e - k) := pow_add 2 k (e - k)
    _ = 0 := by
      have htwo : (2 : ZMod (2 ^ k)) = ((2 : ℕ) : ZMod (2 ^ k)) := by norm_num
      rw [htwo, ← Nat.cast_pow]
      simp

/-- The ideal generated by a finitely indexed family. Keeping the index set
separate is useful during the block construction; repeated generators are
discarded only when the family is converted to the paper's set-valued model. -/
def generatedIdealIdx (s : Finset ι) (G : ι → Finset V) : Finset (Finset V) :=
  s.biUnion fun i ↦ (G i).powerset

/-- Taking powersets preserves finite intersections. -/
def powersetInfHom : InfHom (Finset V) (Finset (Finset V)) :=
  ⟨Finset.powerset, by
    intro a b
    ext u
    simp only [Finset.inf_eq_inter, Finset.mem_powerset, Finset.mem_inter]
    constructor
    · intro h
      exact ⟨fun _ hx ↦ (Finset.mem_inter.1 (h hx)).1,
        fun _ hx ↦ (Finset.mem_inter.1 (h hx)).2⟩
    · rintro ⟨ha, hb⟩ x hx
      exact Finset.mem_inter.2 ⟨ha hx, hb hx⟩⟩

theorem inf'_powerset (s : Finset ι) (hs : s.Nonempty) (G : ι → Finset V) :
    s.inf' hs (fun i ↦ (G i).powerset) = (s.inf' hs G).powerset := by
  change s.inf' hs ((powersetInfHom (V := V)) ∘ G) =
    powersetInfHom (s.inf' hs G)
  exact (map_finset_inf' (powersetInfHom (V := V)) hs G).symm

/-- Inclusion-exclusion specialized to unions of principal ideals.  This is
the algebraic engine of Claim 6.5: every intersection contributes a signed
power of two, whose exponent is the cardinality of the generator intersection. -/
theorem generatedIdealIdx_card_inclusionExclusion
    (s : Finset ι) (G : ι → Finset V) :
    ((generatedIdealIdx s G).card : ℤ) =
      ∑ t : s.powerset.filter (·.Nonempty),
        (-1 : ℤ) ^ (t.1.card + 1) * (2 : ℤ) ^ (t.1.inf' (Finset.mem_filter.1 t.2).2 G).card := by
  unfold generatedIdealIdx
  rw [Finset.inclusion_exclusion_card_biUnion]
  apply Finset.sum_congr rfl
  intro t ht
  congr 1
  rw [inf'_powerset, Finset.card_powerset, Int.natCast_pow]
  simp

def generatorIntersection {s : Finset ι}
    (G : ι → Finset V) (t : s.powerset.filter (·.Nonempty)) : Finset V :=
  t.1.inf' (Finset.mem_filter.1 t.2).2 G

def zmodIETerm {s : Finset ι} (G : ι → Finset V) (k : ℕ)
    (t : s.powerset.filter (·.Nonempty)) : ZMod (2 ^ k) :=
  (-1 : ZMod (2 ^ k)) ^ (t.1.card + 1) *
    (2 : ZMod (2 ^ k)) ^ (generatorIntersection G t).card

theorem generatedIdealIdx_card_zmod (s : Finset ι) (G : ι → Finset V) (k : ℕ) :
    ((generatedIdealIdx s G).card : ZMod (2 ^ k)) =
      ∑ t : s.powerset.filter (·.Nonempty), zmodIETerm G k t := by
  have h := congrArg (fun z : ℤ ↦ (z : ZMod (2 ^ k)))
    (generatedIdealIdx_card_inclusionExclusion s G)
  simpa [zmodIETerm, generatorIntersection] using h

set_option maxHeartbeats 800000 in
/-- Modulo `2^k`, inclusion-exclusion terms whose generator intersection has
at least `k` elements vanish.  `survives` lets a later proof name exactly the
exceptional subfamilies (in Claim 6.5 these are `P(h) ∪ L`, with `L ≠ ∅`). -/
theorem generatedIdealIdx_card_zmod_survivors
    (s : Finset ι) (G : ι → Finset V) (k : ℕ)
    (survives : s.powerset.filter (·.Nonempty) → Prop) [DecidablePred survives]
    (hvanish : ∀ t, ¬ survives t →
      k ≤ (generatorIntersection G t).card) :
    ((generatedIdealIdx s G).card : ZMod (2 ^ k)) =
      ∑ t : s.powerset.filter (·.Nonempty),
        if survives t then zmodIETerm G k t else 0 := by
  rw [generatedIdealIdx_card_zmod]
  apply Finset.sum_congr rfl
  intro t ht
  by_cases hs : survives t
  · simp [hs]
  · simp [hs, zmodIETerm, two_pow_eq_zero_zmod k _ (hvanish t hs)]

/-! A useful simplification for the staged construction: adjoining one fresh
vertex to selected generators adds a layer canonically equivalent to the ideal
generated by the old selected generators. -/

def liftSet (s : Finset V) : Finset (Option V) :=
  s.map Function.Embedding.some

def dropNone (s : Finset (Option V)) : Finset V :=
  s.filterMap id (by
    intro a a' b ha ha'
    cases a <;> cases a' <;> simp_all)

omit [DecidableEq V] in
@[simp] theorem none_not_mem_liftSet (s : Finset V) : none ∉ liftSet s := by
  simp [liftSet]

omit [DecidableEq V] in
@[simp] theorem some_mem_liftSet {x : V} {s : Finset V} :
    some x ∈ liftSet s ↔ x ∈ s := by
  simp [liftSet]

omit [DecidableEq V] in
@[simp] theorem mem_dropNone {x : V} {s : Finset (Option V)} :
    x ∈ dropNone s ↔ some x ∈ s := by
  simp [dropNone]

omit [DecidableEq V] in
theorem reconstruct_without_none {s : Finset (Option V)} (h : none ∉ s) :
    liftSet (dropNone s) = s := by
  ext x
  cases x with
  | none => simp [h]
  | some x => simp

theorem reconstruct_with_none {s : Finset (Option V)} (h : none ∈ s) :
    insert none (liftSet (dropNone s)) = s := by
  ext x
  cases x with
  | none => simp [h]
  | some x => simp

omit [DecidableEq V] in
@[simp] theorem dropNone_liftSet (s : Finset V) : dropNone (liftSet s) = s := by
  ext x
  simp

@[simp] theorem dropNone_insert_none_liftSet (s : Finset V) :
    dropNone (insert none (liftSet s)) = s := by
  ext x
  simp

def liftFinsetEmbedding : Finset V ↪ Finset (Option V) where
  toFun := liftSet
  inj' := fun _ _ h ↦ by
    simpa only [dropNone_liftSet] using congrArg dropNone h

def freshFinsetEmbedding : Finset V ↪ Finset (Option V) where
  toFun s := insert none (liftSet s)
  inj' := fun _ _ h ↦ by
    simpa only [dropNone_insert_none_liftSet] using congrArg dropNone h

def adjoinFresh (chosen : Finset (Finset V)) (s : Finset V) : Finset (Option V) :=
  if s ∈ chosen then insert none (liftSet s) else liftSet s

theorem none_mem_adjoinFresh_iff {chosen : Finset (Finset V)} {s : Finset V} :
    none ∈ adjoinFresh chosen s ↔ s ∈ chosen := by
  by_cases hs : s ∈ chosen <;> simp [adjoinFresh, hs]

theorem some_mem_adjoinFresh_iff {chosen : Finset (Finset V)} {s : Finset V} {x : V} :
    some x ∈ adjoinFresh chosen s ↔ x ∈ s := by
  by_cases hs : s ∈ chosen <;> simp [adjoinFresh, hs]

theorem dropNone_subset_of_subset_adjoinFresh
    {chosen : Finset (Finset V)} {s : Finset V} {t : Finset (Option V)}
    (h : t ⊆ adjoinFresh chosen s) : dropNone t ⊆ s := by
  intro x hx
  rw [mem_dropNone] at hx
  exact some_mem_adjoinFresh_iff.1 (h hx)

theorem subset_adjoinFresh_of_dropNone_subset
    {chosen : Finset (Finset V)} {s : Finset V} {t : Finset (Option V)}
    (ht : dropNone t ⊆ s) (hfresh : none ∈ t → s ∈ chosen) :
    t ⊆ adjoinFresh chosen s := by
  intro x hx
  cases x with
  | none => exact none_mem_adjoinFresh_iff.2 (hfresh hx)
  | some x => exact some_mem_adjoinFresh_iff.2 (ht (mem_dropNone.2 hx))

def stageIdeal (generators chosen : Finset (Finset V)) : Finset (Finset (Option V)) :=
  generatedIdealIdx generators (adjoinFresh chosen)

def liftedIdeal (generators : Finset (Finset V)) : Finset (Finset (Option V)) :=
  (generatedIdealIdx generators id).map liftFinsetEmbedding

def freshIdeal (generators : Finset (Finset V)) : Finset (Finset (Option V)) :=
  (generatedIdealIdx generators id).map freshFinsetEmbedding

/-- Exact decomposition of one stage into the old layer and the new fresh layer. -/
theorem stageIdeal_eq_union_layers
    {generators chosen : Finset (Finset V)} (hchosen : chosen ⊆ generators) :
    stageIdeal generators chosen = liftedIdeal generators ∪ freshIdeal chosen := by
  ext t
  by_cases hnone : none ∈ t
  · constructor
    · intro ht
      rcases Finset.mem_biUnion.1 ht with ⟨s, hsG, hts⟩
      have hsub : t ⊆ adjoinFresh chosen s := Finset.mem_powerset.1 hts
      have hsChosen : s ∈ chosen := none_mem_adjoinFresh_iff.1 (hsub hnone)
      have hdrop : dropNone t ∈ generatedIdealIdx chosen id := by
        apply Finset.mem_biUnion.2
        exact ⟨s, hsChosen, Finset.mem_powerset.2
          (dropNone_subset_of_subset_adjoinFresh hsub)⟩
      apply Finset.mem_union_right
      apply Finset.mem_map.2
      exact ⟨dropNone t, hdrop, reconstruct_with_none hnone⟩
    · intro ht
      rcases Finset.mem_union.1 ht with htOld | htFresh
      · rcases Finset.mem_map.1 htOld with ⟨u, hu, hut⟩
        have hn : none ∉ (liftFinsetEmbedding (V := V)) u := none_not_mem_liftSet u
        exact False.elim (hn (hut ▸ hnone))
      · rcases Finset.mem_map.1 htFresh with ⟨u, hu, hut⟩
        rcases Finset.mem_biUnion.1 hu with ⟨s, hsChosen, hus⟩
        apply Finset.mem_biUnion.2
        refine ⟨s, hchosen hsChosen, Finset.mem_powerset.2 ?_⟩
        rw [← hut]
        apply subset_adjoinFresh_of_dropNone_subset
        · simpa [freshFinsetEmbedding] using Finset.mem_powerset.1 hus
        · exact fun _ ↦ hsChosen
  · constructor
    · intro ht
      rcases Finset.mem_biUnion.1 ht with ⟨s, hsG, hts⟩
      have hsub : t ⊆ adjoinFresh chosen s := Finset.mem_powerset.1 hts
      have hdrop : dropNone t ∈ generatedIdealIdx generators id := by
        apply Finset.mem_biUnion.2
        exact ⟨s, hsG, Finset.mem_powerset.2
          (dropNone_subset_of_subset_adjoinFresh hsub)⟩
      apply Finset.mem_union_left
      apply Finset.mem_map.2
      exact ⟨dropNone t, hdrop, reconstruct_without_none hnone⟩
    · intro ht
      rcases Finset.mem_union.1 ht with htOld | htFresh
      · rcases Finset.mem_map.1 htOld with ⟨u, hu, hut⟩
        rcases Finset.mem_biUnion.1 hu with ⟨s, hsG, hus⟩
        apply Finset.mem_biUnion.2
        refine ⟨s, hsG, Finset.mem_powerset.2 ?_⟩
        rw [← hut]
        apply subset_adjoinFresh_of_dropNone_subset
        · simpa [liftFinsetEmbedding] using Finset.mem_powerset.1 hus
        · intro hn
          exact False.elim (none_not_mem_liftSet u hn)
      · rcases Finset.mem_map.1 htFresh with ⟨u, hu, hut⟩
        have hy : none ∈ (freshFinsetEmbedding (V := V)) u := by
          simp [freshFinsetEmbedding]
        exact False.elim (hnone (hut ▸ hy))

theorem disjoint_liftedIdeal_freshIdeal
    (generators chosen : Finset (Finset V)) :
    Disjoint (liftedIdeal generators) (freshIdeal chosen) := by
  rw [Finset.disjoint_left]
  intro t htOld htFresh
  rcases Finset.mem_map.1 htOld with ⟨u, hu, hut⟩
  rcases Finset.mem_map.1 htFresh with ⟨v, hv, hvt⟩
  have hn : none ∉ (liftFinsetEmbedding (V := V)) u := none_not_mem_liftSet u
  have hy : none ∈ (freshFinsetEmbedding (V := V)) v := by simp [freshFinsetEmbedding]
  exact hn (hut ▸ hvt ▸ hy)

/-- Exact increment formula used implicitly in the paper at every stage. -/
theorem stageIdeal_card
    {generators chosen : Finset (Finset V)} (hchosen : chosen ⊆ generators) :
    (stageIdeal generators chosen).card =
      (generatedIdealIdx generators id).card + (generatedIdealIdx chosen id).card := by
  rw [stageIdeal_eq_union_layers hchosen,
    Finset.card_union_of_disjoint (disjoint_liftedIdeal_freshIdeal generators chosen)]
  simp [liftedIdeal, freshIdeal]

/-! The indexed form is the one used by the block construction. Generator
indices stay fixed through all stages; at the end, duplicate generator sets
can be discarded by taking the image, since only an upper bound on the number
of generators is required. -/

def adjoinFreshIdx [DecidableEq ι]
    (chosen : Finset ι) (G : ι → Finset V) (i : ι) : Finset (Option V) :=
  if i ∈ chosen then insert none (liftSet (G i)) else liftSet (G i)

theorem none_mem_adjoinFreshIdx_iff [DecidableEq ι]
    {chosen : Finset ι} {G : ι → Finset V} {i : ι} :
    none ∈ adjoinFreshIdx chosen G i ↔ i ∈ chosen := by
  by_cases hi : i ∈ chosen <;> simp [adjoinFreshIdx, hi]

theorem some_mem_adjoinFreshIdx_iff [DecidableEq ι]
    {chosen : Finset ι} {G : ι → Finset V} {i : ι} {x : V} :
    some x ∈ adjoinFreshIdx chosen G i ↔ x ∈ G i := by
  by_cases hi : i ∈ chosen <;> simp [adjoinFreshIdx, hi]

theorem dropNone_subset_of_subset_adjoinFreshIdx [DecidableEq ι]
    {chosen : Finset ι} {G : ι → Finset V} {i : ι} {t : Finset (Option V)}
    (h : t ⊆ adjoinFreshIdx chosen G i) : dropNone t ⊆ G i := by
  intro x hx
  exact some_mem_adjoinFreshIdx_iff.1 (h (mem_dropNone.1 hx))

theorem subset_adjoinFreshIdx_of_dropNone_subset [DecidableEq ι]
    {chosen : Finset ι} {G : ι → Finset V} {i : ι} {t : Finset (Option V)}
    (ht : dropNone t ⊆ G i) (hfresh : none ∈ t → i ∈ chosen) :
    t ⊆ adjoinFreshIdx chosen G i := by
  intro x hx
  cases x with
  | none => exact none_mem_adjoinFreshIdx_iff.2 (hfresh hx)
  | some x => exact some_mem_adjoinFreshIdx_iff.2 (ht (mem_dropNone.2 hx))

def indexedStageIdeal [DecidableEq ι]
    (all chosen : Finset ι) (G : ι → Finset V) : Finset (Finset (Option V)) :=
  generatedIdealIdx all (adjoinFreshIdx chosen G)

def liftedIndexedIdeal
    (all : Finset ι) (G : ι → Finset V) : Finset (Finset (Option V)) :=
  (generatedIdealIdx all G).map liftFinsetEmbedding

def freshIndexedIdeal
    (chosen : Finset ι) (G : ι → Finset V) : Finset (Finset (Option V)) :=
  (generatedIdealIdx chosen G).map freshFinsetEmbedding

theorem indexedStageIdeal_eq_union_layers [DecidableEq ι]
    {all chosen : Finset ι} {G : ι → Finset V} (hchosen : chosen ⊆ all) :
    indexedStageIdeal all chosen G =
      liftedIndexedIdeal all G ∪ freshIndexedIdeal chosen G := by
  ext t
  by_cases hnone : none ∈ t
  · constructor
    · intro ht
      rcases Finset.mem_biUnion.1 ht with ⟨i, hiAll, hti⟩
      have hsub : t ⊆ adjoinFreshIdx chosen G i := Finset.mem_powerset.1 hti
      have hiChosen : i ∈ chosen := none_mem_adjoinFreshIdx_iff.1 (hsub hnone)
      apply Finset.mem_union_right
      apply Finset.mem_map.2
      refine ⟨dropNone t, ?_, reconstruct_with_none hnone⟩
      apply Finset.mem_biUnion.2
      exact ⟨i, hiChosen, Finset.mem_powerset.2
        (dropNone_subset_of_subset_adjoinFreshIdx hsub)⟩
    · intro ht
      rcases Finset.mem_union.1 ht with htOld | htFresh
      · rcases Finset.mem_map.1 htOld with ⟨u, hu, hut⟩
        have hn : none ∉ (liftFinsetEmbedding (V := V)) u := none_not_mem_liftSet u
        exact False.elim (hn (hut ▸ hnone))
      · rcases Finset.mem_map.1 htFresh with ⟨u, hu, hut⟩
        rcases Finset.mem_biUnion.1 hu with ⟨i, hiChosen, hui⟩
        apply Finset.mem_biUnion.2
        refine ⟨i, hchosen hiChosen, Finset.mem_powerset.2 ?_⟩
        rw [← hut]
        apply subset_adjoinFreshIdx_of_dropNone_subset
        · simpa [freshFinsetEmbedding] using Finset.mem_powerset.1 hui
        · exact fun _ ↦ hiChosen
  · constructor
    · intro ht
      rcases Finset.mem_biUnion.1 ht with ⟨i, hiAll, hti⟩
      have hsub : t ⊆ adjoinFreshIdx chosen G i := Finset.mem_powerset.1 hti
      apply Finset.mem_union_left
      apply Finset.mem_map.2
      refine ⟨dropNone t, ?_, reconstruct_without_none hnone⟩
      apply Finset.mem_biUnion.2
      exact ⟨i, hiAll, Finset.mem_powerset.2
        (dropNone_subset_of_subset_adjoinFreshIdx hsub)⟩
    · intro ht
      rcases Finset.mem_union.1 ht with htOld | htFresh
      · rcases Finset.mem_map.1 htOld with ⟨u, hu, hut⟩
        rcases Finset.mem_biUnion.1 hu with ⟨i, hiAll, hui⟩
        apply Finset.mem_biUnion.2
        refine ⟨i, hiAll, Finset.mem_powerset.2 ?_⟩
        rw [← hut]
        apply subset_adjoinFreshIdx_of_dropNone_subset
        · simpa [liftFinsetEmbedding] using Finset.mem_powerset.1 hui
        · intro hn
          exact False.elim (none_not_mem_liftSet u hn)
      · rcases Finset.mem_map.1 htFresh with ⟨u, hu, hut⟩
        have hy : none ∈ (freshFinsetEmbedding (V := V)) u := by
          simp [freshFinsetEmbedding]
        exact False.elim (hnone (hut ▸ hy))

theorem disjoint_liftedIndexedIdeal_freshIndexedIdeal
    (all chosen : Finset ι) (G : ι → Finset V) :
    Disjoint (liftedIndexedIdeal all G) (freshIndexedIdeal chosen G) := by
  rw [Finset.disjoint_left]
  intro t htOld htFresh
  rcases Finset.mem_map.1 htOld with ⟨u, hu, hut⟩
  rcases Finset.mem_map.1 htFresh with ⟨v, hv, hvt⟩
  have hn : none ∉ (liftFinsetEmbedding (V := V)) u := none_not_mem_liftSet u
  have hy : none ∈ (freshFinsetEmbedding (V := V)) v := by simp [freshFinsetEmbedding]
  exact hn (hut ▸ hvt ▸ hy)

/-- Indexed exact stage increment; this removes all bookkeeping about actual
generator equality from the induction in Claim 6.6. -/
theorem indexedStageIdeal_card [DecidableEq ι]
    {all chosen : Finset ι} {G : ι → Finset V} (hchosen : chosen ⊆ all) :
    (indexedStageIdeal all chosen G).card =
      (generatedIdealIdx all G).card + (generatedIdealIdx chosen G).card := by
  rw [indexedStageIdeal_eq_union_layers hchosen,
    Finset.card_union_of_disjoint (disjoint_liftedIndexedIdeal_freshIndexedIdeal all chosen G)]
  simp [liftedIndexedIdeal, freshIndexedIdeal]

end AntichainOfGivenSize.Section6
