import Mathlib.Analysis.Asymptotics.Defs
import Mathlib.Analysis.SpecialFunctions.Log.Base
import Mathlib.Data.Finset.Powerset
import Mathlib.Order.Lattice.Nat

/-!
# The improved generating-ideal bound

This file states only the asymptotic bound from Theorem 6.10 of
*Exponentially Smaller Generating Antichains for an Ideal of Prescribed Size*.
-/

open Asymptotics Filter

namespace AntichainOfGivenSize

/-- The ideal generated by a finite family of finite sets:
`ID(S) = ⋃ A ∈ S, 2^A`. -/
def generatedIdeal {V : Type*} [DecidableEq V]
    (generators : Finset (Finset V)) : Finset (Finset V) :=
  generators.biUnion fun generator ↦ generator.powerset

/-- `HasGeneratorCount n k` says that some ideal of cardinality `n` is
generated by a family of exactly `k` sets.

The finite type `Fin m` is a canonical ambient universe: every finite family
of finite sets can be relabelled inside some `Fin m`. -/
def HasGeneratorCount (n k : ℕ) : Prop :=
  ∃ m : ℕ, ∃ generators : Finset (Finset (Fin m)),
    (generatedIdeal generators).card = n ∧ generators.card = k

/-- The paper's `α(n)`: the minimum number of sets needed to generate an
ideal of cardinality exactly `n`. -/
noncomputable def alpha (n : ℕ) : ℕ :=
  sInf {k : ℕ | HasGeneratorCount n k}

/-- The base-2 comparison function
`(log₂(log₂ n))² / log₂(log₂(log₂ n))`. -/
noncomputable def improvedScale (n : ℝ) : ℝ :=
  (Real.logb 2 (Real.logb 2 n)) ^ 2 /
    Real.logb 2 (Real.logb 2 (Real.logb 2 n))

/-- Theorem 6.10 (range-based improved reduction bound):

`alpha(n) = O((log₂(log₂ n))² / log₂(log₂(log₂ n)))`.

Using `atTop` formalizes "for sufficiently large `n`" and makes the values of
the iterated logarithms at the finitely many small inputs irrelevant.
-/
def RangeBasedImprovedReductionBound : Prop :=
  (fun n : ℕ ↦ (alpha n : ℝ)) =O[atTop]
    (fun n : ℕ ↦ improvedScale n)

end AntichainOfGivenSize
