import Mathlib.Analysis.Asymptotics.Defs
import Mathlib.Analysis.SpecialFunctions.Log.Base
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.Nat.Bits
import Mathlib.Order.Lattice.Nat

/-!
# Problem definition and main statements

This is the proof-free audit surface for the main results. It contains the
problem definitions, the explicit block-count witness recursion, and the
main public theorem claims. No proof implementation is imported here.

All logarithms are base `2`. The asymptotic upper bound holds for all
sufficiently large inputs; the matching lower bound holds infinitely often.
The sharp block-count upper bound holds at every input and is attained for
every positive block count.
-/

open Asymptotics Filter

namespace AntichainOfGivenSize

/-! ## Problem definition -/

/-- The ideal generated by a finite family `S`:
`ID(S) = ⋃ A ∈ S, 2^A`. -/
def generatedIdeal {V : Type*} [DecidableEq V]
    (generators : Finset (Finset V)) : Finset (Finset V) :=
  generators.biUnion fun generator ↦ generator.powerset

/-- A family is an inclusion antichain when two members related by inclusion
are necessarily equal. -/
def IsInclusionAntichain {V : Type*} [DecidableEq V]
    (generators : Finset (Finset V)) : Prop :=
  ∀ ⦃A⦄, A ∈ generators → ∀ ⦃B⦄, B ∈ generators →
    A ⊆ B → A = B

/-- `HasAntichainGeneratorCount n k` is the paper-facing representation
predicate: an inclusion antichain of exactly `k` sets generates an ideal with
exactly `n` members. -/
def HasAntichainGeneratorCount (n k : ℕ) : Prop :=
  ∃ m : ℕ, ∃ generators : Finset (Finset (Fin m)),
    IsInclusionAntichain generators ∧
      (generatedIdeal generators).card = n ∧ generators.card = k

/-- `HasGeneratorCount n k` means that an ideal with exactly `n` members is
generated by exactly `k` sets.

The finite type `Fin m` is a canonical ambient universe. Every finite family
of finite sets can be relabelled inside one of these universes. This
implementation-facing predicate permits redundant generators. -/
def HasGeneratorCount (n k : ℕ) : Prop :=
  ∃ m : ℕ, ∃ generators : Finset (Finset (Fin m)),
    (generatedIdeal generators).card = n ∧ generators.card = k

/-- `α(n)`, the minimum number of generators of an ideal with `n` members.

`mainAlphaHasAntichainWitness` certifies that this unrestricted minimum is
attained by an inclusion antichain, and hence agrees with the paper's
generating-antichain definition. -/
noncomputable def alpha (n : ℕ) : ℕ :=
  sInf {k : ℕ | HasGeneratorCount n k}

/-! ## Binary blocks and explicit extremal integers -/

/-- The number of maximal runs of `1`s in the binary expansion of `n`,
called `bl(n)` in *CNFs and DNFs with Exactly k Solutions*. For example,
`49 = 110001₂` has two such runs. In particular,
`binaryBlockCount 0 = 0`.

These binary runs are unrelated to the sets called blocks in the Section 6
upper-bound construction in this repository. -/
def binaryBlockCount : ℕ → ℕ :=
  Nat.binaryRec 0 fun b n count ↦
    count + if b && !n.bodd then 1 else 0

namespace BlockCount

/-- Coarse upper bound for the number of singleton and pair exponents. -/
def exponentBudget (k : ℕ) : ℕ := k * (k + k * k)

/-- Coarse lower-bound loss for all intersections inside one cluster. -/
def finiteClusterRadius (p k H : ℕ) : ℕ :=
  H + k * k * (2 * (p + 1 + H))

/-- Number of extra bits used to separate the grid from all error terms. -/
def scalePadding (k : ℕ) : ℕ := exponentBudget k + 2

/-- Successive scale cutoffs. The starting cutoff is positive. -/
def finiteScale (p k : ℕ) : ℕ → ℕ
  | 0 => 1
  | j + 1 => finiteClusterRadius p k (finiteScale p k j) + scalePadding k

/-- A sufficient shift for the finite reduction lemma, with `p` itself used
as a simple upper bound for all normalized generator exponents. -/
def finiteThreshold (p k : ℕ) : ℕ :=
  finiteScale p k (exponentBudget k + 1)

/-- A concrete recursion attaining the block-count bound. It starts at
`explicitBlockWitness 1 = 3` and, for `b ≥ 1`, sets
`n_(b+1) = 2 ^ (explicitWitnessShift b) * n_b + 1`.
The value at zero is included only to make the function total. -/
def explicitBlockWitness : ℕ → ℕ
  | 0 => 0
  | 1 => 3
  | b + 2 =>
      2 ^ (max 2 (finiteThreshold (explicitBlockWitness (b + 1)) (b + 2))) *
        explicitBlockWitness (b + 1) + 1

/-- The chosen shift is at least two and at least the sufficient threshold. -/
def explicitWitnessShift (b : ℕ) : ℕ :=
  max 2 (finiteThreshold (explicitBlockWitness b) (b + 1))

end BlockCount

/-! ## Common asymptotic scale -/

/-- The scale occurring in both main bounds:
`(log₂(log₂ n))² / log₂(log₂(log₂ n))`. -/
noncomputable def quadraticLogLogScale (n : ℝ) : ℝ :=
  (Real.logb 2 (Real.logb 2 n)) ^ 2 /
    Real.logb 2 (Real.logb 2 (Real.logb 2 n))

/-- Historical name for `quadraticLogLogScale`. -/
noncomputable abbrev improvedScale := quadraticLogLogScale

/-! ## Main theorem statements -/

/-- **Main upper bound.** For all sufficiently large `n`,
`α(n) = O((log₂ log₂ n)² / log₂ log₂ log₂ n)`. -/
def UpperBoundStatement : Prop :=
  (fun n : ℕ ↦ (alpha n : ℝ)) =O[atTop]
    (fun n : ℕ ↦ quadraticLogLogScale n)

/-- **Main lower bound.** A fixed positive multiple of the same scale is a
lower bound for `α(n)` at arbitrarily large inputs. -/
def LowerBoundStatement : Prop :=
  ∃ c : ℝ, 0 < c ∧ ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧
    c * quadraticLogLogScale n ≤ (alpha n : ℝ)

/-- The explicit lower bound proved here, with constant `1 / 4096`. -/
def ExplicitLowerBoundStatement : Prop :=
  ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧
    (1 / 4096 : ℝ) * quadraticLogLogScale n ≤ (alpha n : ℝ)

/-- The minimum generator count is attained by an inclusion antichain. -/
def AlphaAntichainWitnessStatement : Prop :=
  ∀ n : ℕ, HasAntichainGeneratorCount n (alpha n)

/-- The binary block count gives the paper's pointwise logarithmic lower bound. -/
def BlockCountLowerBoundStatement : Prop :=
  ∀ n : ℕ,
    Real.logb 2 ((binaryBlockCount n + 1 : ℕ) : ℝ) ≤ (alpha n : ℝ)

/-- The elementary pointwise upper bound from the binary block count. -/
def BlockCountUpperBoundStatement : Prop :=
  ∀ n : ℕ, alpha n ≤ binaryBlockCount n + 1

/-- Both pointwise block-count inequalities, for every natural number.
The lower bound is logarithmic; the upper bound is linear. -/
def BlockCountBoundsStatement : Prop :=
  BlockCountLowerBoundStatement ∧ BlockCountUpperBoundStatement

/-- The pointwise upper bound is attained at every positive block count. -/
def BlockCountTightBoundStatement : Prop :=
  ∀ b : ℕ, 0 < b →
    (∀ n : ℕ, binaryBlockCount n = b → alpha n ≤ b + 1) ∧
      ∃ n : ℕ, 0 < n ∧ binaryBlockCount n = b ∧ alpha n = b + 1

/-- The explicit recursive integer attains the bound at every positive block count. -/
def ExplicitBlockWitnessStatement : Prop :=
  ∀ b : ℕ, 0 < b →
    0 < BlockCount.explicitBlockWitness b ∧
      binaryBlockCount (BlockCount.explicitBlockWitness b) = b ∧
      alpha (BlockCount.explicitBlockWitness b) = b + 1

/-! ## Compatibility name -/

/-- Historical internal name for `UpperBoundStatement`. -/
abbrev RangeBasedImprovedReductionBound : Prop := UpperBoundStatement

end AntichainOfGivenSize
