import Mathlib.Analysis.Asymptotics.Defs
import Mathlib.Analysis.SpecialFunctions.Log.Base
import Mathlib.Data.Finset.Powerset
import Mathlib.Order.Lattice.Nat

/-!
# Problem definition and main statements

This is the audit surface for the main result. It contains exactly the
definitions needed to state the problem, followed by the matching upper and
lower bounds. No construction or proof implementation is imported here.

All logarithms are base `2`. The upper bound holds for all sufficiently large
inputs, while the lower bound is a worst-case (infinitely-often) statement.
-/

open Asymptotics Filter

namespace AntichainOfGivenSize

/-! ## Problem definition -/

/-- The ideal generated by a finite family `S`:
`ID(S) = ⋃ A ∈ S, 2^A`. -/
def generatedIdeal {V : Type*} [DecidableEq V]
    (generators : Finset (Finset V)) : Finset (Finset V) :=
  generators.biUnion fun generator ↦ generator.powerset

/-- A family is an inclusion antichain when two members related by inclusion
are necessarily equal. -/
def IsInclusionAntichain {V : Type*} [DecidableEq V]
    (generators : Finset (Finset V)) : Prop :=
  ∀ ⦃A⦄, A ∈ generators → ∀ ⦃B⦄, B ∈ generators →
    A ⊆ B → A = B

/-- `HasAntichainGeneratorCount n k` is the paper-facing representation
predicate: an inclusion antichain of exactly `k` sets generates an ideal with
exactly `n` members. -/
def HasAntichainGeneratorCount (n k : ℕ) : Prop :=
  ∃ m : ℕ, ∃ generators : Finset (Finset (Fin m)),
    IsInclusionAntichain generators ∧
      (generatedIdeal generators).card = n ∧ generators.card = k

/-- `HasGeneratorCount n k` means that an ideal with exactly `n` members is
generated by exactly `k` sets.

The finite type `Fin m` is a canonical ambient universe. Every finite family
of finite sets can be relabelled inside one of these universes. This
implementation-facing predicate permits redundant generators. -/
def HasGeneratorCount (n k : ℕ) : Prop :=
  ∃ m : ℕ, ∃ generators : Finset (Finset (Fin m)),
    (generatedIdeal generators).card = n ∧ generators.card = k

/-- `α(n)`, the minimum number of generators of an ideal with `n` members.

`mainAlphaHasAntichainWitness` certifies that this unrestricted minimum is
attained by an inclusion antichain, and hence agrees with the paper's
generating-antichain definition. -/
noncomputable def alpha (n : ℕ) : ℕ :=
  sInf {k : ℕ | HasGeneratorCount n k}

/-! ## Common asymptotic scale -/

/-- The scale occurring in both main bounds:
`(log₂(log₂ n))² / log₂(log₂(log₂ n))`. -/
noncomputable def quadraticLogLogScale (n : ℝ) : ℝ :=
  (Real.logb 2 (Real.logb 2 n)) ^ 2 /
    Real.logb 2 (Real.logb 2 (Real.logb 2 n))

/-- Historical name for `quadraticLogLogScale`. -/
noncomputable abbrev improvedScale := quadraticLogLogScale

/-! ## Main theorem statements -/

/-- **Main upper bound.** For all sufficiently large `n`,
`α(n) = O((log₂ log₂ n)² / log₂ log₂ log₂ n)`. -/
def UpperBoundStatement : Prop :=
  (fun n : ℕ ↦ (alpha n : ℝ)) =O[atTop]
    (fun n : ℕ ↦ quadraticLogLogScale n)

/-- **Main lower bound.** A fixed positive multiple of the same scale is a
lower bound for `α(n)` at arbitrarily large inputs. -/
def LowerBoundStatement : Prop :=
  ∃ c : ℝ, 0 < c ∧ ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧
    c * quadraticLogLogScale n ≤ (alpha n : ℝ)

/-- The explicit lower bound proved here, with constant `1 / 4096`. -/
def ExplicitLowerBoundStatement : Prop :=
  ∀ N : ℕ, ∃ n : ℕ, N ≤ n ∧
    (1 / 4096 : ℝ) * quadraticLogLogScale n ≤ (alpha n : ℝ)

/-! ## Compatibility name -/

/-- Historical internal name for `UpperBoundStatement`. -/
abbrev RangeBasedImprovedReductionBound : Prop := UpperBoundStatement

end AntichainOfGivenSize
